In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_inp = tf.placeholder(tf.float32, [5, 5])
w_inp = tf.placeholder(tf.float32, [3, 3])

In [3]:
x = tf.reshape(x_inp, [1, 5, 5, 1])
w = tf.reshape(w_inp, [3, 3, 1, 1])

In [4]:
x_valid = tf.nn.conv2d(x, w, strides=[1, 1, 1, 1], padding="VALID")
x_same = tf.nn.conv2d(x, w, strides=[1, 1, 1, 1], padding="SAME")
x_valid_half = tf.nn.conv2d(x, w, strides=[1, 2, 2, 1], padding="VALID")
x_same_half = tf.nn.conv2d(x, w, strides=[1, 2, 2, 1], padding="SAME")

In [24]:
sess = tf.Session()
y_valid, y_same, y_valid_half, y_same_half = sess.run(
    [x_valid, x_same, x_valid_half, x_same_half], feed_dict={x_inp: x, w_inp: w})

TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.

In [25]:
x_inp = tf.placeholder(tf.float32, [4, 4])
x = tf.reshape(x_inp, [1, 4, 4, 1])

In [26]:
x_valid = tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 1, 1, 1],
padding="VALID")
x_valid_half = tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1],
padding="VALID")

In [27]:
x = np.array([[0, 1, 2, 1],
[4, 1, 0, 1],
[2, 0, 1, 1],
[1, 2, 3, 1]])
y_valid, y_valid_half = sess.run(
[x_valid, x_valid_half],
feed_dict={x_inp: x}
)

In [29]:
print("padding=VALID:\n", y_valid[0, :, :, 0])
print("padding=VALID, stride 2:\n", y_valid_half[0, :, :, 0])

padding=VALID:
 [[ 4.  2.  2.]
 [ 4.  1.  1.]
 [ 2.  3.  3.]]
padding=VALID, stride 2:
 [[ 4.  2.]
 [ 2.  3.]]
